[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NZ-SeQTech"
authors = [{name = "N.Innan and MAZ. Khan", email = "nouhailainnan@gmail.com"}]
dynamic = ["version", "description"]
